In [1]:
import pandas as pd
import numpy as nd

In [2]:
price_per_category=pd.Series({'product A': 12500, 'product B': 13599, 'product C':11500})
price_per_category

product A    12500
product B    13599
product C    11500
dtype: int64

In [5]:
price_per_category.values

array([12500, 13599, 11500], dtype=int64)

In [7]:
type(price_per_category.values)

numpy.ndarray

In [9]:
price_per_category.array

<PandasArray>
[12500, 13599, 11500]
Length: 3, dtype: int64

In [11]:
type(price_per_category.array)

pandas.core.arrays.numpy_.PandasArray

In [14]:
price_per_category.to_numpy()

array([12500, 13599, 11500], dtype=int64)

In [16]:
type(price_per_category.to_numpy())

numpy.ndarray

In [19]:
test_array=price_per_category[['product A','product B','product C']].to_numpy(dtype='float')
test_array

array([12500., 13599., 11500.])

In [22]:
price_per_category.values[0]

12500

In [24]:
type(price_per_category.values[0])

numpy.int64

In [26]:
price_per_category.array[0]

12500

In [29]:
price_per_category.to_numpy()[0]

12500